- project:
    name: 'pe-config-management-ui'
    meta_path_project: 'enterprise/production/pe-config-management-ui.yaml'
    value_stream: 'enterprise'

    github_user: 'puppetlabs'
    github_project: 'pe-config-management-ui'

    hipchat_room:
        - 'Configuration Management'

    assets-outdirs: "resources/config-management-ui/dist"
    assets-builddir: "dev-resources/config-management-ui"
    testem-port: 7359

    kickoff_disabled: False
    jobs:
        - 'pe-ui-ember-cli-pipeline':
            scm_branch: 'master'
            downstream_jobs:
              - 'enterprise_pe-console-ui_compose-console-master'
